<?php

$masterTextbookList = array('01' => array('id' => '01',
										'fName' => 'Jack',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'02' => array('id' => '02',
										'fName' => 'Betty',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'03' => array('id' => '03',
										'fName' => 'Carl',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'04' => array('id' => '04',
										'fName' => 'Mary',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'05' => array('id' => '05',
										'fName' => 'Venkatesh',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'06' => array('id' => '06',
										'fName' => 'Ipsita',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'07' => array('id' => '07',
										'fName' => 'Bayezin',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'08' => array('id' => '08',
										'fName' => 'Dilani',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'09' => array('id' => '09',
										'fName' => 'Rohit',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'10' => array('id' => '10',
										'fName' => 'Jonathan',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'11' => array('id' => '11',
										'fName' => 'Danielle',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'12' => array('id' => '12',
										'fName' => 'Charles',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'13' => array('id' => '13',
										'fName' => 'Vinita',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'14' => array('id' => '14',
										'fName' => 'Conrad',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'15' => array('id' => '15',
										'fName' => 'Lindsey',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'16' => array('id' => '16',
										'fName' => 'Sushen',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'17' => array('id' => '17',
										'fName' => 'Gwynneth',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'18' => array('id' => '18',
										'fName' => 'Alex',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'19' => array('id' => '19',
										'fName' => 'Preetjot',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'20' => array('id' => '20',
										'fName' => 'Kala',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'21' => array('id' => '21',
										'fName' => 'Terry',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'22' => array('id' => '22',
										'fName' => 'Judy',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'23' => array('id' => '23',
										'fName' => 'William',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'24' => array('id' => '24',
										'fName' => 'Monika',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'25' => array('id' => '25',
										'fName' => 'Duy',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'26' => array('id' => '26',
										'fName' => 'Jeffery',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'27' => array('id' => '27',
										'fName' => 'Michelle',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'28' => array('id' => '28',
										'fName' => 'Shan',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'29' => array('id' => '29',
										'fName' => 'Judy',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg'), 
					'30' => array('id' => '30',
										'fName' => 'Emily',
										'title' => 'English Basics',
										'price' => '35',
										'description' => 'Last years edition.',
										'photos' => '325.jpg;495.jpg;491.jpg;235.jpg') 

	);
?>